'use client';
import { LearnerSetup } from "./learner-profile";
import { defaultLearnerProfile, type LearnerProfile } from "@/lib/api";
import { useCallback, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, BookOpen, Code2, MessageCircle } from 'lucide-react';
import { api, Auth, Course } from '@/lib/api';
import Shell from './shell';

type Feedback = { verdict: string; explanation: string; correct_approach: string; revision_tasks: string[] };
type Coding = { title: string; language: string; problem: string; starter_code: string; hints: string[]; solution: string; explanation: string; complexity: string };
type Lesson = { requirement_id: string; title: string; concepts: string; example: string; mistakes: string[]; readiness: string[]; minutes: number; coding: Coding | null };
type Activity = { id: string; kind: string; title: string; minutes: number; date: string; pinned: boolean };
type Plan = { start_date: string; end_date?: string; expired?: boolean; days: number; daily_minutes: number; activities: Activity[]; backlog: (Activity & { reason: string })[]; shortfall_minutes: number; conflicts: { date: string; minutes: number; budget: number }[] };
type Interview = { id: string; mode: string; minutes: number; status: string; revision: number; messages: { role: string; text: string; feedback?: string; revision_tasks?: string[] }[]; feedback: { feedback?: string; revision_tasks?: string[] } };
type Practice = { learner_profile?: LearnerProfile; revision: number; state: { session?: { current?: string; queue?: string[] }; reviews?: Record<string, { confidence: number; reviewed_at: string }>; drafts?: Record<string, string>; feedback?: Record<string, { answer: string | null; feedback: Feedback }>; completed?: Record<string, string>; plan?: Plan }; learning: { lessons?: Lesson[]; resources?: { id: string; title: string; url: string; minutes: number; kind: string; verified_at: string }[]; limitations?: string[]; note?: string }; learning_stale: boolean; missing_lesson_ids: string[]; ordered_card_ids: string[]; summary: { reviewed: number; total: number; coverage: number; confidence: Record<string, number> }; weak_spots?: { id: string; topic: string; kind: string; priority: string; total: number; reviewed: number; confidence: number | null }[]; weak_topics: { id: string; text: string }[]; interviews: Interview[]; history: { id: string; kind: string; created_at: string; payload: { item_id?: string; answer?: string; feedback?: Feedback; command?: { item_id: string; confidence: number } } }[] };
type Job = { id: string; status: string; completed_steps: number; total_steps: number; can_retry: boolean; error?: { message: string }; steps: { label: string; status: string }[] };
type Workload = { daily_minutes: number; days: { date: string; minutes: number; over_by: number }[]; unplanned_courses: string[] };

function FeedbackView({ feedback }: { feedback: Feedback }) {
  return <div className="practice-feedback"><span className="eyebrow">AI COACH FEEDBACK · CODE WAS NOT EXECUTED</span><h3>{feedback.verdict.replace('_', ' ')}</h3><p className="study-answer">{feedback.explanation}</p><h4>A better approach</h4><p className="study-answer">{feedback.correct_approach}</p><ul>{feedback.revision_tasks.map((s, i) => <li key={i}>{s}</li>)}</ul></div>;
}

function Exercise({ identity, title, problem, coding, saved, feedback, busy, cache, onSave, onSubmit }: { identity: string; title: string; problem: string; coding?: Coding; saved: string; feedback?: { answer: string | null; feedback: Feedback }; busy: boolean; cache: Record<string, string>; onSave: (id: string, value: string) => Promise<boolean>; onSubmit: (id: string, value: string) => Promise<boolean> }) {
  const [draft, setDraft] = useState(cache[identity] ?? (saved || coding?.starter_code || ''));
  const [persisted, setPersisted] = useState(saved || coding?.starter_code || '');
  const [saving, setSaving] = useState(false);
  const dirty = draft !== persisted;
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (dirty) e.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, [dirty]);
  async function save(submit: boolean) { setSaving(true); const value = draft; try { if (await (submit ? onSubmit : onSave)(identity, value)) { setPersisted(value); delete cache[identity]; } } finally { setSaving(false); } }
  return <article className="exercise" aria-label={title}><div className="exercise-problem"><h3>{title}</h3><p className="study-answer">{problem}</p>{coding && <><span className="badge">{coding.language}</span><details><summary>Need a hint?</summary><ol>{coding.hints.map((hint, i) => <li key={i}>{hint}</li>)}</ol></details><details><summary>Reveal the solution</summary><pre>{coding.solution}</pre><h4>Line-by-line explanation</h4><p className="study-answer">{coding.explanation}</p><h4>Complexity</h4><p>{coding.complexity}</p></details></>}</div>
    <div><label>{coding ? 'Your code' : 'Your answer'}<textarea className={coding ? 'code-editor' : 'answer-editor'} aria-label={coding ? 'Your code' : 'Your answer'} spellCheck={!coding} value={draft} onChange={e => { cache[identity] = e.target.value; setDraft(e.target.value); }} onKeyDown={e => { if (coding && e.key === 'Tab' && !e.shiftKey) { e.preventDefault(); const node = e.currentTarget; const start = node.selectionStart, end = node.selectionEnd; cache[identity] = draft.slice(0, start) + '  ' + draft.slice(end); setDraft(cache[identity]); requestAnimationFrame(() => { node.selectionStart = node.selectionEnd = start + 2; }); } }} /></label><p className="field-help">{coding ? `${draft.split('\n').length} lines · Tab indents · Shift+Tab leaves the editor. ` : ''}{dirty ? 'Unsaved changes — save before switching exercises.' : 'Draft ready.'}</p><div className="editor-actions"><button className="secondary" disabled={saving || busy} onClick={() => void save(false)}>{saving ? 'Saving…' : 'Save draft'}</button><button className="primary" disabled={saving || busy || !draft.trim()} onClick={() => void save(true)}>Get feedback</button></div><p className="field-help">Your attempt is saved before the coach responds. Feedback explains the answer; it does not run your code.</p></div>
    {feedback && <div className="exercise-feedback">{feedback.answer !== draft && <p className="field-help">Feedback on your previous submitted answer.</p>}<FeedbackView feedback={feedback.feedback} /></div>}
  </article>;
}

export default function PracticeWorkspace({ auth, id }: { auth: Auth; id: string }) {
  const [course, setCourse] = useState<Course | null>(null);
  const draftCache = useRef<Record<string, string>>({});
  useEffect(() => { const warn = (e: BeforeUnloadEvent) => { if (Object.keys(draftCache.current).length) e.preventDefault(); }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn); }, []);
  const [data, setData] = useState<Practice | null>(null);
  const current = useRef<Practice | null>(null);
  const [tab, setTab] = useState('Today');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const mutating = useRef(false);
  const [job, setJob] = useState<Job | null>(null);
  const [events, setEvents] = useState<{ id: number; created_at: string; message: string }[]>([]);
  const [workload, setWorkload] = useState<Workload | null>(null);
  const [revealed, setRevealed] = useState(false);
  const [lessonId, setLessonId] = useState('');
  const [exerciseId, setExerciseId] = useState('');
  const [interviewId, setInterviewId] = useState('');
  const [reply, setReply] = useState('');
  const [mode, setMode] = useState('teaching');
  const [minutes, setMinutes] = useState(15);
  const [days, setDays] = useState(14);
  const [dailyMinutes, setDailyMinutes] = useState(120);
  const update = useCallback((next: Practice) => { current.current = next; setData(next); }, []);
  const load = useCallback(async () => {
    const [c, p, jobs, w] = await Promise.all([api<{ course: Course }>(`/courses/${id}`), api<Practice>(`/courses/${id}/practice`), api<{ jobs: Job[] }>(`/courses/${id}/jobs`), api<Workload>('/workload')]);
    setCourse(c.course); update(p); setWorkload(w); const latest = jobs.jobs.find(j => ['queued', 'running', 'retry_wait'].includes(j.status)) || jobs.jobs[0] || null; setJob(latest); if (latest) setEvents((await api<{ events: { id: number; created_at: string; message: string }[] }>(`/jobs/${latest.id}?limit=200`)).events);
    return { course: c.course, practice: p };
  }, [id, update]);
  useEffect(() => { void load().then(({ course, practice }) => { setDays(practice.state.plan?.days || course.days); setDailyMinutes(practice.state.plan?.daily_minutes || course.daily_minutes); }).catch(e => setError(e.message)); }, [load]);
  const active = !!job && ['queued', 'running', 'retry_wait'].includes(job.status);
  useEffect(() => {
    if (!active || !job) return;
    let cancelled = false;
    const timer = setTimeout(async () => { try { const result = await api<{ job: Job; events: { id: number; created_at: string; message: string }[] }>(`/jobs/${job.id}?limit=200`); if (cancelled) return; setEvents(result.events); setJob(result.job); if (!['queued', 'running', 'retry_wait'].includes(result.job.status)) await load(); } catch (e) { if (!cancelled) { setError((e as Error).message); setJob(j => j ? { ...j } : j); } } }, 1200);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [active, job, load]);
  async function command(action: string, fields: Record<string, unknown> = {}) {
    if (mutating.current || !current.current) return false;
    mutating.current = true; setBusy(true); setError('');
    try { update(await api<Practice>(`/courses/${id}/practice`, { method: 'POST', body: JSON.stringify({ action, revision: current.current.revision, request_key: crypto.randomUUID(), ...fields }) }, auth.csrf_token)); return true; }
    catch (e) { setError((e as Error).message); return false; }
    finally { mutating.current = false; setBusy(false); }
  }
  async function generate(kind: string, fields: Record<string, unknown> = {}) {
    if (mutating.current || !current.current) return false;
    mutating.current = true; setBusy(true); setError('');
    try { const result = await api<{ job: Job }>(`/courses/${id}/practice/generate`, { method: 'POST', body: JSON.stringify({ kind, revision: current.current.revision, request_key: crypto.randomUUID(), ...fields }) }, auth.csrf_token); setEvents([]); setJob(result.job); update(await api<Practice>(`/courses/${id}/practice`)); return true; }
    catch (e) { setError((e as Error).message); return false; }
    finally { mutating.current = false; setBusy(false); }
  }
  const lessons = data?.learning.lessons || [];
  const lesson = lessons.find(l => l.requirement_id === lessonId) || lessons[0];
  const cardId = data?.state.session?.current;
  const card = course?.kit?.flashcards.find(c => c.id === cardId);
  const coding = lessons.filter(l => l.coding);
  const exercises = [...(course?.kit?.questions || []).map(q => ({ id: 'answer:' + q.id, title: q.prompt, problem: q.prompt, coding: undefined as Coding | undefined, answer: q.answer_outline })), ...coding.map(l => ({ id: 'code:' + l.requirement_id, title: l.coding!.title, problem: l.coding!.problem, coding: l.coding!, answer: '' }))];
  const exercise = exercises.find(x => x.id === exerciseId) || exercises[0];
  const interview = data?.interviews.find(i => i.id === interviewId) || data?.interviews[0];
  const plan = data?.state.plan;
  function openActivity(a: Activity) { if (a.kind === 'reading') { setLessonId(a.id.replace('read:', '')); setTab('Reading'); } else if (['coding', 'assignment'].includes(a.kind)) { setExerciseId(a.id); setTab('Assignments'); } else if (a.kind === 'external_resource') setTab('Reading'); else if (a.kind === 'mock_interview') setTab('Interview'); else setTab('Flashcards'); }

  return <Shell auth={auth}><Link className="back-link" href={`/courses/${id}`}><ArrowLeft size={15} /> Course overview</Link><div className="page-heading"><div><span className="eyebrow">YOUR PRACTICE SPACE</span><h1>{course?.title || 'Prepare for your interview'}</h1><p>Learn a little. Try it yourself. Come back stronger.</p></div>{data && <div className="practice-progress"><strong>{data.summary.coverage}%</strong><span>cards reviewed · {data.summary.reviewed}/{data.summary.total}</span></div>}</div>
    {error && <div className="panel practice-error"><p role="alert">{error}</p><button className="secondary" onClick={() => void load().then(() => setError('')).catch(e => setError(e.message))}>Reload saved practice</button></div>}
    {!data || !course ? <p role="status">Loading practice…</p> : <>
      {job && (active || ['failed', 'blocked'].includes(job.status)) && <div className="practice-job" role="status"><strong>{active ? `Preparing · ${job.completed_steps}/${job.total_steps} steps` : 'The last request needs attention'}</strong><p>{active ? job.steps.find(s => s.status !== 'completed')?.label : job.error?.message}</p><details><summary>Saved progress</summary>{job.steps.map((s, i) => <p key={i}>{s.label} · {s.status}</p>)}</details>{job.can_retry && <button className="secondary" onClick={async () => { try { setJob((await api<{ job: Job }>(`/jobs/${job.id}/retry`, { method: 'POST' }, auth.csrf_token)).job); } catch (e) { setError((e as Error).message); } }}>Retry saved request</button>}</div>}
      <div className="study-tabs practice-tabs" role="tablist" aria-label="Practice sections">{['Today', 'Reading', 'Flashcards', 'Assignments', 'Interview', 'Weak spots'].map(t => <button key={t} role="tab" aria-selected={tab === t} onClick={() => setTab(t)}>{t}</button>)}</div>
      <section className="panel practice-panel" role="tabpanel" aria-label={tab}>
        {tab === 'Today' && <><LearnerSetup value={data.learner_profile || defaultLearnerProfile} requirements={course.kit?.role.requirements || []} disabled={busy || active} onSave={profile => command('profile', { learner_profile: profile })} /><h2>Your next steps</h2><p className="field-help">Completed work stays saved when you replan. Generation completion and learning progress are separate.</p><div className="practice-settings"><label>Days remaining<input aria-label="Days remaining" type="number" min={1} max={60} value={days} onChange={e => setDays(Number(e.target.value))} /></label><label>Minutes per day<input aria-label="Minutes per day" type="number" min={15} max={480} value={dailyMinutes} onChange={e => setDailyMinutes(Number(e.target.value))} /></label><button className="secondary" disabled={busy} onClick={() => void command('replan', { days, daily_minutes: dailyMinutes }).then(() => api<Workload>('/workload').then(setWorkload))}>Replan unfinished work</button></div>
          {data.learning_stale && <p className="generation-intro-note">Your level or topics have changed. Refresh reading materials in the Reading tab to get matching explanations. Completed work remains saved.</p>}{!lessons.length && <div className="practice-empty"><BookOpen size={24} /><h3>Build your reading course</h3><p>Get focused lessons for each topic, worked examples and coding exercises where useful.</p><button className="primary" disabled={active || busy} onClick={() => void generate('lessons')}>Generate reading materials</button></div>}
          {plan && <>{plan.expired && <p className="generation-intro-note">Your planned interview date has passed. Update days remaining to schedule more preparation.</p>}{plan.shortfall_minutes > 0 && <p className="generation-intro-note" role="status">Required work needs {plan.shortfall_minutes} more minutes. Increase your time or reprioritise your courses; the remaining tasks are listed below.</p>}{plan.conflicts.map(c => <p className="error" key={c.date}>{c.date}: {c.minutes} minutes planned against {c.budget} available. Move unfinished work to resolve this.</p>)}
            {Array.from(new Set(plan.activities.map(a => a.date))).map(date => <div className="practice-day" key={date}><h3>{date} <span className="field-help">{plan.activities.filter(a => a.date === date).reduce((n, a) => n + a.minutes, 0)} min</span></h3>{plan.activities.filter(a => a.date === date).map(a => <div className="practice-activity" key={a.id}><button className="text-link" onClick={() => openActivity(a)}>{data.state.completed?.[a.id] && <Check size={15} />}{a.title}</button><span>{a.kind.replace('_', ' ')} · {a.minutes} min</span><div>{!data.state.completed?.[a.id] && <><button className="secondary" disabled={busy} onClick={() => void command('complete', { item_id: a.id })}>Mark done</button><input type="date" aria-label={`Move ${a.title}`} value={a.date} disabled={busy} onChange={e => void command('move', { item_id: a.id, day: e.target.value })} /></>}</div></div>)}</div>)}
            {!!plan.backlog.length && <details><summary>{plan.backlog.length} tasks waiting for time</summary>{plan.backlog.map(t => <p key={t.id}>{t.title} · {t.minutes} min · {t.reason}</p>)}</details>}</>}
          {workload && course.availability_scope === 'shared' && <details className="workload"><summary>Shared workload across your courses</summary><button className="secondary" disabled={busy || active} onClick={async () => { setBusy(true); try { await api("/workload/rebalance", { method: "POST", body: JSON.stringify({ course_ids: [id] }) }, auth.csrf_token); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>Prioritise this course and rebalance</button><p>Shared daily allowance: {workload.daily_minutes} minutes. Earlier planned courses keep their slots; replan lower-priority courses afterwards.</p>{workload.days.map(d => <p key={d.date}>{d.date} · {d.minutes} min {d.over_by > 0 && <strong>· {d.over_by} min over capacity</strong>}</p>)}{!!workload.unplanned_courses.length && <p>{workload.unplanned_courses.length} course(s) still need a practice plan.</p>}</details>}
          {!!data.weak_topics.length && <details><summary>Topics to revisit</summary><ul>{data.weak_topics.map(r => <li key={r.id}>{r.text}</li>)}</ul></details>}
        </>}
        {tab === 'Weak spots' && <><span className="eyebrow">MAKE YOUR NEXT SESSION COUNT</span><h2>Know where to focus</h2><p className="weak-intro">Confidence comes from your own card reviews: Needs work = 0%, Developing = 50%, Confident = 100%. Each topic averages its reviewed cards. Unseen cards are shown separately.</p><div className="weak-grid">{(data.weak_spots || []).map(topic => <article className="weak-card" key={topic.id}><div className="generation-heading"><span className="badge">{topic.kind}</span><span className="research-meta">{topic.priority === 'must' ? 'Required' : 'Nice to have'}</span></div><h3>{topic.topic}</h3><div className="weak-score"><strong>{!topic.total ? 'No cards yet' : topic.confidence === null ? 'Not reviewed' : topic.confidence + '%'}</strong><span>self-reported confidence</span></div><progress aria-label={topic.topic + ' confidence'} max={100} value={topic.confidence ?? 0} /><p>{topic.reviewed} of {topic.total} cards reviewed</p><button className="secondary full" disabled={busy || !topic.total} onClick={() => void command('session', { item_id: topic.id }).then(ok => { if (ok) { setRevealed(false); setTab('Flashcards'); } })}>Practise this topic</button></article>)}</div>{!data.weak_spots?.length && <p>Add requirements and flashcards to see your focus areas.</p>}</>}
        {tab === 'Reading' && <><div className="generation-heading"><h2>Focused reading</h2>{lessons.length && !data.missing_lesson_ids.length && !data.learning_stale ? <span className="field-help">All chapters saved and ready to read</span> : <button className="secondary" disabled={active || busy} onClick={() => void generate('lessons')}>{lessons.length ? 'Update reading materials' : 'Generate reading materials'}</button>}</div>{data.learning_stale && <p className="generation-intro-note">Your role or preparation level has changed. Refresh these lessons to match your current needs.</p>}{!!data.missing_lesson_ids.length && <p className="field-help">{data.missing_lesson_ids.length} topics still need reading material.</p>}{lesson && <><label>Choose a lesson<select aria-label="Choose a lesson" value={lesson.requirement_id} onChange={e => setLessonId(e.target.value)}>{lessons.map(l => <option key={l.requirement_id} value={l.requirement_id}>{l.title}</option>)}</select></label><article className="reading-lesson"><span className="eyebrow">{lesson.minutes} MINUTE READ</span><h2>{lesson.title}</h2><p className="study-answer">{lesson.concepts}</p><h3>A practical example</h3><p className="study-answer">{lesson.example}</p><h3>Common mistakes</h3><ul>{lesson.mistakes.map((m, i) => <li key={i}>{m}</li>)}</ul><h3>Ready when you can…</h3><ul>{lesson.readiness.map((m, i) => <li key={i}>{m}</li>)}</ul><div className="editor-actions"><button className="primary" disabled={busy || !!data.state.completed?.['read:' + lesson.requirement_id]} onClick={() => void command('complete', { item_id: 'read:' + lesson.requirement_id })}>{data.state.completed?.['read:' + lesson.requirement_id] ? 'Reading completed' : 'Mark reading complete'}</button>{lesson.coding && <button className="secondary" onClick={() => { setExerciseId('code:' + lesson.requirement_id); setTab('Assignments'); }}><Code2 size={16} /> Try the coding exercise</button>}</div></article></>}<details><summary>Optional videos and playlists</summary><p>Focused resources are optional and use remaining time after core practice. Playlists are considered for plans of 21 days or more.</p><button className="secondary" disabled={active || busy} onClick={() => void generate("resources")}>Find verified resources</button>{data.learning.limitations?.map((l, i) => <p key={i}>{l}</p>)}{data.learning.note && <p className="field-help">{data.learning.note}</p>}{data.learning.resources?.map(r => <p key={r.id}><a href={r.url} target="_blank" rel="noopener noreferrer">{r.title}</a> ? {r.minutes} min ? {r.kind}</p>)}</details></>}
        {tab === 'Flashcards' && <><div className="generation-heading"><h2>Recall, then reveal</h2><span className="badge">{data.summary.reviewed} reviewed · {data.summary.total - data.summary.reviewed} unseen</span></div><p className="field-help">Unseen cards first, then lower confidence, oldest review and stable ID. Confidence is your self-assessment, not an exam score.</p><p className="confidence-summary">Needs work: {data.summary.confidence['1']} · Developing: {data.summary.confidence['2']} · Confident: {data.summary.confidence['3']}</p>
          {!card ? <div className="practice-empty"><h3>{data.summary.total ? 'Ready for a review?' : 'No flashcards yet'}</h3><p>{data.summary.total ? 'A new session prioritises what you have not seen and what feels less familiar.' : 'Add flashcards in the course editor to begin.'}</p><button className="primary" disabled={busy || !data.summary.total} onClick={() => void command('session').then(() => setRevealed(false))}>Start review session</button></div> : <article className="recall-card"><span className="eyebrow">{data.state.session?.queue?.length} CARDS LEFT IN THIS SESSION</span><h2>{card.front}</h2>{!revealed ? <button className="primary" onClick={() => setRevealed(true)}>Reveal answer</button> : <><p className="study-answer">{card.back}</p><p>How confident do you feel?</p><div className="editor-actions">{['Needs work', 'Developing', 'Confident'].map((label, i) => <button className="secondary" key={label} disabled={busy} onClick={() => void command('review', { item_id: card.id, confidence: i + 1 }).then(ok => { if (ok) setRevealed(false); })}>{label}</button>)}</div></>}{coding.filter(l => card.requirement_ids.includes(l.requirement_id)).map(l => <button key={l.requirement_id} className="text-link" onClick={() => { setExerciseId('code:' + l.requirement_id); setTab('Assignments'); }}><Code2 size={15} /> Practise this in code</button>)}</article>}
          <details><summary>Review history</summary>{data.history.filter(h => h.kind === 'review').map(h => <p key={h.id}>{new Date(h.created_at).toLocaleString()} · {course.kit?.flashcards.find(c => c.id === h.payload.command?.item_id)?.front || 'Previous card'} · Confidence {h.payload.command?.confidence}/3</p>)}</details></>}
        {tab === 'Assignments' && <><h2>Try it, then learn from it</h2><p>Write your approach or code. The coach will explain what to improve and why.</p>{exercise ? <><label>Choose an exercise<select aria-label="Choose an exercise" value={exercise.id} onChange={e => setExerciseId(e.target.value)}>{exercises.map(x => <option key={x.id} value={x.id}>{x.coding ? 'Code: ' : ''}{x.title}</option>)}</select></label><Exercise key={exercise.id} identity={exercise.id} title={exercise.title} problem={exercise.problem} coding={exercise.coding} saved={data.state.drafts?.[exercise.id] || ''} cache={draftCache.current} feedback={data.state.feedback?.[exercise.id]} busy={busy || active} onSave={(item_id, text) => command('draft', { item_id, text })} onSubmit={(item_id, text) => generate('feedback', { item_id, text })} />{exercise.answer && <details><summary>Reveal the answer and approach</summary><p className="study-answer">{exercise.answer}</p></details>}</> : <p>Add questions or generate reading materials to practise an exercise.</p>}<details><summary>Saved attempts</summary>{data.history.filter(h => h.kind === 'feedback').map(h => <article key={h.id}><p>{new Date(h.created_at).toLocaleString()} · {h.payload.item_id}</p><pre>{h.payload.answer}</pre>{h.payload.feedback && <FeedbackView feedback={h.payload.feedback} />}</article>)}</details></>}
        {tab === 'Interview' && <><div className="generation-heading"><div><MessageCircle size={22} /><h2>Live interview practice</h2></div><span className="badge">Interactive text</span></div><p>Answer in your own words, ask follow-up questions, and practise with a coach that responds to you.</p><p className="field-help">Session length is an approximate question budget (one answer per three minutes). Leave and resume without losing your conversation.</p>
          {data.interviews.length > 0 && <label>Saved interviews<select aria-label="Saved interviews" value={interview?.id || ''} onChange={e => setInterviewId(e.target.value)}>{data.interviews.map((s, i) => <option value={s.id} key={s.id}>Session {data.interviews.length - i} · {s.mode} · {s.status}</option>)}</select></label>}
          {(!interview || interview.status === 'completed') && <div className="practice-settings"><label>Interview mode<select aria-label="Interview mode" value={mode} onChange={e => setMode(e.target.value)}><option value="teaching">Teaching · immediate explanations</option><option value="simulation">Simulation · feedback at the end</option></select></label><label>Session minutes<input aria-label="Session minutes" type="number" min={5} max={60} value={minutes} onChange={e => setMinutes(Number(e.target.value))} /></label><button className="primary" disabled={busy || active} onClick={() => void generate('interview', { mode, minutes }).then(ok => { if (ok) { setInterviewId(''); setReply(''); } })}>Start live interview</button></div>}
          {interview && <><div className="conversation" aria-label="Interview conversation">{interview.messages.map((m, i) => <article className={`conversation-message ${m.role}`} key={i}><span className="eyebrow">{m.role === 'user' ? 'YOU' : 'INTERVIEWER'}</span>{m.feedback && <p className="study-answer">{m.feedback}</p>}{m.text && <p className="study-answer">{m.text}</p>}{!!m.revision_tasks?.length && <ul>{m.revision_tasks.map((r, j) => <li key={j}>{r}</li>)}</ul>}</article>)}</div>{interview.status === 'active' ? <><label>Your reply<textarea aria-label="Your reply" value={reply} maxLength={3000} onChange={e => setReply(e.target.value)} placeholder="Explain your thinking, or ask the interviewer a question…" /></label><div className="editor-actions"><button className="primary" disabled={busy || active || !reply.trim()} onClick={() => void generate('interview', { interview_id: interview.id, interview_revision: interview.revision, text: reply }).then(ok => { if (ok) setReply(''); })}>Send reply</button><button className="secondary" disabled={busy || active} onClick={() => void generate('interview', { interview_id: interview.id, interview_revision: interview.revision, text: reply, finish: true }).then(ok => { if (ok) setReply(''); })}>Finish and get feedback</button></div></> : <p className="generation-intro-note">Session complete. Your conversation and revision tasks are saved.</p>}</>}
        </>}
      </section>
    </>}
  </Shell>;
}
