import { test, expect } from '@playwright/test';
import { mockMissingProvider } from './generation-fixture';

test('register, save multiple courses, edit, import, refresh, and sign back in', async ({ page }) => {
  await mockMissingProvider(page);
  const email = `browser-${Date.now()}@example.com`;
  const password = 'browser-test-password';
  await page.goto('/');
  await expect(page).toHaveURL(/\/login$/);
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByLabel('Full name').fill('Taylor');
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My courses' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'A place for your next interview.' })).toBeVisible();
  await page.getByRole('link', { name: 'New course', exact: true }).click();
  await page.getByLabel('Course name').fill('Frontend at Linear');
  await page.getByPlaceholder('Company name', { exact: true }).fill('Linear');
  await page.getByLabel('Company website').fill('https://linear.app');
  await page.getByLabel('Job description').fill('Frontend engineer. Required: React, TypeScript and accessible interfaces.');
  await page.getByLabel('Days until interview').fill('14');
  await page.getByLabel('Study hours per day').fill('2');
  await page.getByRole('button', { name: 'Create and generate course', exact: true }).click();
  await expect(page).toHaveURL(/\/courses\/[0-9a-f-]+$/);
  await page.getByRole('link', { name: 'All courses', exact: true }).click();
  const card = page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Frontend at Linear', exact: true }) });
  await expect(card).toBeVisible();
  await card.click();
  await expect(page.getByRole('heading', { name: 'Frontend at Linear', exact: true })).toBeVisible();
  await page.getByLabel('Course name').fill('Senior Frontend at Linear');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByText('Changes saved.', { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Course name')).toHaveValue('Senior Frontend at Linear');
  await page.getByRole('link', { name: 'All courses', exact: true }).click();
  await page.getByRole('link', { name: 'New course', exact: true }).click();
  await page.getByRole('button', { name: 'Import multiple' }).click();
  await page.getByLabel('Batch JSON file').setInputFiles({ name: 'cases.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify([{ id: 'backend-case', jd: 'Python and SQL required.', company_url: 'https://example.org', days: 7 }])) });
  await page.getByRole('button', { name: 'Import and generate courses' }).click();
  await expect(page).toHaveURL(/\/courses\/[0-9a-f-]+$/);
  await page.getByRole('link', { name: 'All courses', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'backend-case', exact: true })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('heading', { name: 'My courses' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Sign out' }).click();
  await expect(page).toHaveURL(/\/login$/);
  await page.getByLabel('Email address').fill(email);
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Senior Frontend at Linear', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'backend-case', exact: true })).toBeVisible();
  await page.getByRole('link').filter({ has: page.getByRole('heading', { name: 'Senior Frontend at Linear', exact: true }) }).click();
  await page.getByRole('button', { name: 'Start generation', exact: true }).click();
  await page.reload();
  await expect(page.getByText('2 of 17 steps complete', { exact: true })).toBeVisible({ timeout: 15000 });
  await expect(page.getByText('Job analysis needs a configured Gemini provider. Ask the administrator to configure GEMINI_API_KEY, then retry this run.', { exact: true }).first()).toBeVisible();
  const history = page.locator('.generation-logs li');
  await expect(history).toHaveCount(8);
  await page.reload();
  await expect(history).toHaveCount(8);
  await expect(page.getByText('2 of 17 steps complete', { exact: true })).toBeVisible();
  await page.screenshot({ path: 'test-results/generation-progress.png', fullPage: true });
});
