import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

test('record the real application walkthrough', async ({ browser, request }) => {
  test.skip(process.env.RECORD_WALKTHROUGH !== '1', 'Explicit live provider and recording opt-in');
  const registered = await request.post('/api/auth/register', { headers: { Origin: 'http://localhost:3000' }, data: { name: 'Walkthrough demo', email: `walkthrough-${Date.now()}@example.com`, password: 'walkthrough-demo-password-123' } });
  expect(registered.status()).toBe(201);
  const auth = await registered.json();
  const headers = { Origin: 'http://localhost:3000', 'X-CSRF-Token': auth.csrf_token };
  const created = await request.post('/api/courses', { headers, data: { title: 'Frontend Engineer at Harbour Tools', company_name: 'Harbour Tools (fixture)', company_url: 'https://example.com', jd: 'Frontend Engineer. Required: build accessible React interfaces. Bonus: TypeScript.', days: 14, daily_minutes: 120 } });
  const { course } = await created.json();
  execFileSync(process.execPath, ['--import', 'tsx', path.resolve('../scripts/prepare-walkthrough.ts'), course.id], { cwd: path.resolve('..'), stdio: ['pipe', 'pipe', 'pipe'], timeout: 180000 });
  await request.post('/api/courses', { headers, data: { title: 'Python Engineer - next interview', company_url: 'https://example.com', jd: 'Python required.', days: 21, daily_minutes: 120 } });
  const context = await browser.newContext({ baseURL: 'http://localhost:3000', storageState: await request.storageState(), viewport: { width: 1366, height: 900 }, recordVideo: { dir: 'test-results/walkthrough-video', size: { width: 1366, height: 900 } } });
  const page = await context.newPage();
  const started = Date.now();
  async function caption(text: string, seconds = 12) {
    await page.evaluate(text => { let node = document.getElementById('walkthrough-caption'); if (!node) { node = document.createElement('div'); node.id = 'walkthrough-caption'; document.body.append(node); } node.textContent = text; node.style.cssText = 'position:fixed;z-index:99999;bottom:14px;left:8%;right:8%;padding:18px 24px;background:#10251ff5;color:white;border-radius:10px;font:18px/1.5 Arial;box-shadow:0 4px 20px #0003;pointer-events:none'; }, text);
    await page.waitForTimeout(seconds * 1000);
  }
  await page.goto('/');
  await caption('Ahead: a separate preparation course for every interview. This demo uses fictional company fixtures and real Gemini-generated content.', 15);
  await page.getByRole('link', { name: 'New course', exact: true }).click();
  await caption('Paste a job description or upload a PDF to extract it. Review the company details and set your preparation time. JSON is optional for bulk imports.', 14);
  await page.goto(`/courses/${course.id}`);
  await caption('The kit contains a company brief, role requirements, categorised questions, flashcards and an exact 14-day schedule.', 14);
  await page.getByRole('tab', { name: 'Daily plan', exact: true }).click();
  await caption('Scheduling and coverage are application code, not model guesses. Every required topic must have a question and appear in the schedule.', 13);
  const generation = page.getByRole('region', { name: 'Course generation', exact: true });
  await generation.scrollIntoViewIfNeeded();
  await caption('A controlled coverage test: one topic’s initial questions were withheld. The real checker found the gap, Gemini repaired it, and validation passed. These are saved execution logs.', 22);
  await page.getByRole('button', { name: 'Edit course', exact: true }).click();
  await page.getByRole('tab', { name: 'Questions', exact: true }).click();
  const first = page.getByRole('article', { name: 'Question 1', exact: true });
  await first.getByLabel('Answer outline', { exact: true }).fill('My interview checklist: explain keyboard navigation, visible focus, semantic HTML and a concrete accessibility test.');
  await first.getByRole('button', { name: 'Pin', exact: true }).click();
  await expect(page.getByText('All changes saved', { exact: true })).toBeVisible();
  await caption('Inline changes autosave. Edited and pinned questions are protected during regeneration. Reordering and category changes are also saved.', 15);
  await page.getByLabel('Section to regenerate').selectOption('questions_technical');
  await page.getByRole('button', { name: 'Regenerate section', exact: true }).click();
  await caption('Refresh just the technical section. The worker generates a proposal, then merges it against the latest saved edits instead of replacing your work.', 12);
  await expect.poll(async () => (await (await page.request.get(`/api/courses/${course.id}/jobs`)).json()).jobs[0]?.status, { timeout: 120000, intervals: [2000] }).toBe('completed');
  await page.reload();
  await page.getByRole('button', { name: 'Edit course', exact: true }).click();
  await page.getByRole('tab', { name: 'Questions', exact: true }).click();
  await expect(page.getByRole('article', { name: 'Question 1', exact: true }).getByLabel('Answer outline', { exact: true })).toHaveValue('My interview checklist: explain keyboard navigation, visible focus, semantic HTML and a concrete accessibility test.');
  const saved = (await (await page.request.get(`/api/courses/${course.id}`)).json()).course;
  expect(saved.kit.questions.some((q: { answer_outline: string }) => q.answer_outline.startsWith('My interview checklist'))).toBeTruthy();
  await caption('After regeneration and refresh, the personal answer and pin remain. Stale-tab saves are rejected rather than silently overwriting content.', 13);
  await page.getByRole('link', { name: 'Open practice', exact: true }).click();
  await page.getByRole('tab', { name: 'Flashcards', exact: true }).click();
  await page.getByRole('button', { name: 'Start review session' }).click();
  await caption('Practice one card at a time. Recall the answer first, reveal it, then record confidence. The session can be resumed after leaving.', 12);
  await page.getByRole('button', { name: 'Reveal answer' }).click();
  await caption('Confidence is separate from coverage. Future sessions prioritise unseen cards, then lower confidence and older reviews.', 12);
  await page.getByRole('button', { name: 'Needs work', exact: true }).click();
  await page.getByRole('tab', { name: 'Weak spots', exact: true }).click();
  await caption('Weak spots show confidence by topic, distinguish unseen cards and start a focused review for the area you choose.', 12);
  await page.getByRole('tab', { name: 'Today', exact: true }).click();
  await page.getByRole('button', { name: 'Replan unfinished work' }).click();
  await caption('The practice planner preserves completed work, shares time across courses and shows shortfalls instead of promising an impossible workload.', 15);
  await page.getByRole('tab', { name: 'Assignments', exact: true }).click();
  await caption('Assignments save your draft and can explain mistakes with AI feedback. Coding exercises and live text interviews extend the required flashcard flow.', 12);
  await page.goto('/');
  await caption('Preparation progress is stored per course. The reviewed-card percentage does not pretend to measure mastery or interview readiness.', 12);
  const remaining = 190000 - (Date.now() - started);
  if (remaining > 0) await page.waitForTimeout(Math.min(remaining, 45000));
  const video = page.video();
  await page.close();
  await video!.saveAs(path.resolve('../output/phase-7-walkthrough.webm'));
  await context.close();
});
